version: "3.8"

services:
  client:
    build: /client
    ports:
      - "5173:5173"
    env_file:
      - /client/.env
    depends_on:
      - backend

  backend:
    build: /backend
    ports:
      - "8000:8000"
    env_file:
      - /backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: smartcrop
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: smartcropdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
